version: '3.8'
services:
  mysql:
    image: mysql:latest
    volumes:
      - C:\dockerData\mysql-8-develop:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_MYSQL_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_MYSQL_NAME}
      MYSQL_USER: ${DATABASE_MYSQL_USER}
      MYSQL_PASSWORD: ${DATABASE_MYSQL_PASSWORD}
    ports:
      - ${DATABASE_MYSQL_PORT}:3306
    networks:
      - develop

networks:
  develop:
    driver: bridge
