import { HEADERS, HEADERS_VALUE } from './enum';

export const READERS_RESPONSE = {
	[HEADERS.CONTENT_TYPE]: HEADERS_VALUE.APPLICATION_JSON,
	[HEADERS.ACCESS_CONTROL_ALLOW_HEADERS]: HEADERS_VALUE.ALLOW,
	[HEADERS.ACCESS_CONTROL_ALLOW_ORIGIN]: HEADERS_VALUE.ALLOW,
	[HEADERS.ACCESS_CONTROL_ALLOW_METHODS]: HEADERS_VALUE.ALLOW,
};
export const MIN_WORD = 1;
export const MAX_WORD = 50;
